name: dev-cd

on:
  push:
    branches:
      - "develop"
      - "SCRUM-117"

permissions:
  contents: read
  checks: write
  actions: read
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/Dev_CI.yml
    secrets: inherit

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setting dev-secret.yml
        run: |
          echo "${{ secrets.DEV_SECRET_YML }}" > ./src/main/resources/dev-secret.yml

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: bootJar with Gradle
        run: ./gradlew :api-owner:bootJar --info

      - name: Change artifact file name
        run: mv build/libs/*.jar build/libs/app.jar

      - name: Upload artifact file
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: ./build/libs/app.jar
          if-no-files-found: error

      - name: Upload deploy scripts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-scripts
          path: ./scripts/dev/
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: dev-owner

    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: ~/app

      - name: Download deploy scripts
        uses: actions/download-artifact@v4
        with:
          name: deploy-scripts
          path: ~/app/scripts

      - name: Replace application to latest
        run: sudo sh ~/app/scripts/replace-new-version.sh
